# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df689d381428d32576484637e6895db0345bbdd83c2c4ea14d4face31975ba883be31ad1f94bb65b01381b3a2c362959d684d0b42e6b587867af16ab2a5b59fe

test:
  secret_key_base: c0f0e50b134428bc1f9bbacb5110156c399e2012d47b351c6b0e859959a15c054084b4f39696d0e81d73557d87bb4334d4c0ce6f5e30aafbe298724dfb998ae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
